// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"LL_StandingPictureMV","status":true,"description":"メッセージウィンドウ表示時に立ち絵を表示します。","parameters":{"sPictures":"[\"{\\\"id\\\":\\\"0\\\",\\\"imageName\\\":\\\"Package1_5\\\",\\\"origin\\\":\\\"0\\\",\\\"x\\\":\\\"438\\\",\\\"y\\\":\\\"298\\\",\\\"x2\\\":\\\"318\\\",\\\"y2\\\":\\\"298\\\",\\\"reverse\\\":\\\"-1\\\",\\\"scaleX\\\":\\\"100\\\",\\\"scaleY\\\":\\\"100\\\",\\\"opacity\\\":\\\"255\\\",\\\"blendMode\\\":\\\"0\\\"}\",\"{\\\"id\\\":\\\"1\\\",\\\"imageName\\\":\\\"Package2_3\\\",\\\"origin\\\":\\\"0\\\",\\\"x\\\":\\\"438\\\",\\\"y\\\":\\\"298\\\",\\\"x2\\\":\\\"318\\\",\\\"y2\\\":\\\"298\\\",\\\"reverse\\\":\\\"-1\\\",\\\"scaleX\\\":\\\"100\\\",\\\"scaleY\\\":\\\"100\\\",\\\"opacity\\\":\\\"255\\\",\\\"blendMode\\\":\\\"0\\\"}\"]","picture1Settings":"","transition":"1","foreFront":"false","picture2Settings":"","transition2":"1","foreFront2":"false","focusToneAdjust":"-96","catheBootPicture":"true"}}
];
